### ISSUE TITLE
Hackage readme refers to Bitbucket issue queue, which does not exist

### ISSUE THREAD

**Issue by beerendlauwers** [haskell/text-icu#22]
On https://hackage.haskell.org/package/text-icu, we see:

> Please report bugs via the [bitbucket issue tracker](http://bitbucket.org/bos/text-icu/issues).

Following that link, we get:

> This repository does not have issue tracking enabled.
> Use the links at the top to get back.

I take it the Github issue queue is used nowadays?

**Comment by vshabanov** [comment]
Fixed
