### ISSUE TITLE
Release a new version to hackage

### ISSUE THREAD

**Issue by niteria** [haskell/text-icu#26]
a4bdf45ac7e28eadf1c3f52ebc10d9546d3c3959 is the change I'd like to see released.

**Comment by watashi** [comment]
ping

**Comment by L-TChen** [comment]
Same here.

**Comment by pepeiborra** [comment]
I am happy to help with this if you give PepeIborra powers in Hackage

**Comment by andreasabel** [comment]
This issue is fixed and can be closed.
