### ISSUE TITLE
Pacman workaround for Windows not working anymore

### ISSUE THREAD

**Issue by afraca** [haskell/text-icu#40]
Any package with text-icu as dependency on Windows can **build** fine with `stack build` , but with `stack ghci` will **fail** with:
```
ghc.EXE:  | C:\sr\snapshots\7501d5b7\lib\x86_64-windows-ghc-8.2.2\text-icu-0.7.0.1-1gkLXKbDLhmLamnawnVRsL\HStext-icu-0.7.0.1-1gkLXKbDLhmLamnawnVRsL.o: unknown symbol `ucnv_getMaxCharSize_61'                                                  
ghc.EXE: unable to load package `text-icu-0.7.0.1'
``` 

Somewhere in the past, this command fixed it: 
`stack exec -- pacman -Sy mingw64/mingw-w64-x86_64-icu `
but this is not sufficient anymore.

**Comment by Mistuke** [comment]
Are you on Windows 10? Microsoft has started shipping icuuc with Windows but an older version. Older ghci gave preference to this version so it broke text-icu. `Ghc 8.4` or `8.6` should work fine.
