### ISSUE TITLE
Declare pkg-config dependencies

### ISSUE THREAD

**Issue by bgamari** [haskell/text-icu#42]
The cabal file should explicitly state the package's pkg-config dependencies using the `pkgconfig-depends`.

**Comment by andreasabel** [comment]
The solution taken so far only declares the needed libraries, but not their _version_:
https://github.com/haskell/text-icu/blob/7830071e9e13db07cf661fa9ec6aba3a0a5e36a1/text-icu.cabal#L61
The `pkgconfig-depends` field allows to give a version range, see https://cabal.readthedocs.io/en/3.6/cabal-package.html#pkg-field-pkgconfig-depends .

I think a version lower bound like `>= 69.1` (or whatever is correct, I don't know) should be added.
I know for sure that `text-icu-0.8.0` does not build with some old versions of the ICU library!
