### ISSUE TITLE
Missing Directions.

### ISSUE THREAD

**Issue by ekmett** [haskell/text-icu#44]
The following direction codes were added later to ICU.

U_FIRST_STRONG_ISOLATE        = 19
U_LEFT_TO_RIGHT_ISOLATE       = 20
U_RIGHT_TO_LEFT_ISOLATE       = 21
U_POP_DIRECTIONAL_ISOLATE     = 22

The `Direction` enum doesn't include them.

This came up when binding the bidirectional algorithm bits of ICU in a separate package and trying to share types with `text-icu`.

**Comment by tkx68** [comment]
This is now fixed meanwhile.
/close

**Comment by vshabanov** [comment]
`text-icu-0.8.0` now supports these new direction codes:
https://hackage.haskell.org/package/text-icu-0.8.0/docs/Data-Text-ICU-Char.html#t:Direction
