### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by andreasabel** [haskell/text-icu#58]
@vshabanov : Thanks for your work on this package!
Would be great to see some GitHub Actions here that perform continuous integration.

**Comment by andreasabel** [comment]
I am satisfied now with the state of the CI now.  
It gives evidence for buildability with serveral GHCs (#61) and on several platforms (#59).

Loose ends:
- CI using stack
- Windows CI running testsuite

However, I am not planning to work more on this for now.

**Comment by vshabanov** [comment]
Thank you a lot for implementing the CI.

I fixed the Windows CI in #69. It turned out it was just a missing path to MSYS, which caused the test not to find the ICU .dll files.
