### ISSUE TITLE
Installation instructions for text-icu-0.8.0 ?

### ISSUE THREAD

**Issue by andreasabel** [haskell/text-icu#59]
What is necessary to install v0.8.0?
```
$ cabal install text-icu-0.8.0
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] next goal: text-icu (user goal)
[__0] rejecting: text-icu-0.8.0 (conflict: pkg-config package icu-i18n-any,
not found in the pkg-config database)
```
The change log says: https://github.com/haskell/text-icu/blob/7830071e9e13db07cf661fa9ec6aba3a0a5e36a1/changelog.md#L7
- But the README does not have updated installation instructions.
- The linked PR is mute on the why and how: https://github.com/haskell/text-icu/pull/43
- Same for the original issue: #42

See also the build failure in the Agda CI: https://github.com/agda/agda/runs/5042362762?check_suite_focus=true#step:7:408

**Comment by vshabanov** [comment]
There's the same error in Hackage
https://hackage.haskell.org/package/text-icu-0.8.0/reports/1

It says:

    NumberFormatter.hsc:25:10: fatal error: unicode/unumberformatter.h: No such file or directory

`unicode/unumberformatter.h` was added in ICU 60. So I suppose that an older ICU version is installed on both Hackage and Agda CI.

Could you check what `libicu` version is installed in Agda CI? Perhaps you need to update it.

It's also interesting whom I could ask to update `libicu` on the Hackage build server.

**Comment by andreasabel** [comment]
> It's also interesting whom I could ask to update `libicu` on the Hackage build server.

Maybe @davean ?

**Comment by andreasabel** [comment]
@vshabanov wrote:
> ```
> NumberFormatter.hsc:25:10: fatal error: unicode/unumberformatter.h: No such file or directory
> ```
> 
> `unicode/unumberformatter.h` was added in ICU 60. So I suppose that an older ICU version is installed on both Hackage and Agda CI.
> 
> Could you check what `libicu` version is installed in Agda CI? Perhaps you need to update it.

Indeed, this error was fixed by going from the `ubunutu-2018` vm (Ubuntu 18.04 LTS) to `ubuntu-latest` (Ubuntu 20.04 LTS), see https://github.com/agda/agda/runs/5066391230?check_suite_focus=true .

**Comment by vshabanov** [comment]
I've made a little update of README in 6219dbfcfb577759991f6a0afdc50396ae961184, and opened an issue about updating `libicu` on the Hackage build server https://github.com/haskell/hackage-server/issues/999

**Comment by andreasabel** [comment]
See #65 for stack/windows.
I still have to figure out cabal/windows.
