### ISSUE TITLE
Expose encoding-guessing functions

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell/text-icu#8]
http://userguide.icu-project.org/conversion/detection seems to say that ICU is able to make some guesses regarding encoding used but text-icu seems to not expose any such functionality which IMHO greatly impairs its usefulness.

**Comment by bos** [comment]
Pull request welcome, I won't have time to implement this myself.

**Comment by bos** [comment]
#27 implements this, and needs just a little reformatting.

**Comment by vshabanov** [comment]
#27 merged and released:
https://hackage.haskell.org/package/text-icu-0.8.0/docs/Data-Text-ICU-CharsetDetection.html
