### ISSUE TITLE
macOS 12: Dynamic linking problem: `symbol not found in flat namespace (_u_charDigitValue_72)`

### ISSUE THREAD

**Issue by andreasabel** [haskell/text-icu#88]
Since I upgraded macOS from 10.14 to 12.6.3 (Monterey), I cannot build anything using `text-icu`.  Linking fails with `dlopen(..): symbol not found in flat namespace (...)`.  However, inspecting the dylib with `dyld_info -symbolic_fixups` produces an entry for the "missing" symbol:
```
$ cabal test
....
<no location info>: error:
    dlopen($ROOT/dist-newstyle/build/x86_64-osx/ghc-9.6.0.20230210/text-icu-0.8.0.2/build/libHStext-icu-0.8.0.2-inplace-ghc9.6.0.20230210.dylib, 0x0005): 
  symbol not found in flat namespace (_u_charDigitValue_72)

$  dyld_info -symbolic_fixups $ROOT/dist-newstyle/build/x86_64-osx/ghc-9.6.0.20230210/text-icu-0.8.0.2/build/libHStext-icu-0.8.0.2-inplace-ghc9.6.0.20230210.dylib \
  | grep charDigit
           +0xC87A0      bind pointer   flat-namespace/_u_charDigitValue_72

```

I sometimes see at the end of a `cabal build`:
```
ld: warning: -undefined dynamic_lookup may not work with chained fixups
```
But this seems harmless: https://gitlab.haskell.org/ghc/ghc/-/issues/22429

**Comment by vshabanov** [comment]
I don't have access to macOS 12, so can't help here. But I will accept any PR fixing this.

**Comment by andreasabel** [comment]
I haven't found any useful information on this problem.  It might be that my system is misconfigured after the upgrade.
I couldn't reproduce this on the `macos-12` virtual environment: https://github.com/haskell/text-icu/actions/runs/4265404589/jobs/7424698129

**Comment by Bodigrim** [comment]
I'm on macOS 13 and `cabal test` works fine after following the instruction in `README`:
```
brew install icu4c
export PKG_CONFIG_PATH="$(brew --prefix)/opt/icu4c/lib/pkgconfig"
```

**Comment by andreasabel** [comment]
I fixed it by `brew uninstall icu4c && brew install icu4c`.  
Brew does not seem aware that its installed libraries might break by migrating the OS; it would refuse to just reinstall/repair upon `brew install icu4c`.  So a hard uninstall of `icu4c` was necessary.
