### ISSUE TITLE
Test failure: missing `BlockCode`s ?

### ISSUE THREAD

**Issue by andreasabel** [haskell/text-icu#94]
The CI on macOS for GHC 9.6 reports a failed test case (ICU_VER=73.2):
https://github.com/haskell/text-icu/actions/runs/6341389638/job/17224925448#step:11:26
```
t_blockCode: [Failed]
*** Failed! (after 76 tests):
Exception:
  toEnum{BlockCode}: tag (322) is outside of enumeration's range (0,320)
  CallStack (from HasCallStack):
    error, called at Data/Text/ICU/Char.hsc:485:17 in text-icu-0.8.0.2-inplace:Data.Text.ICU.Char
'\203257'
```
The Windows CI has a similar test failure (ICU_VER=73.2):
https://github.com/haskell/text-icu/actions/runs/6341389638/job/17224926997#step:11:25
```
  t_blockCode: [Failed]
*** Failed! (after 47 tests):
Exception:
  toEnum{BlockCode}: tag (322) is outside of enumeration's range (0,320)
  CallStack (from HasCallStack):
    error, called at Data\Text\ICU\Char.hsc:485:17 in text-icu-0.8.0.2-inplace:Data.Text.ICU.Char
'\201586'
```

These could be symptomatic that `text-icu` has fallen behind the ICU lib.
ICU 72 has Unicode 15, but currently only ICU 70 is supported.

I suppose this package needs some updates to the state of the art.
ATTN: @vshabanov

**Comment by andreasabel** [comment]
https://github.com/haskell/text-icu/actions/runs/6361312691/job/17275646782#step:11:957
```
  t_blockCode: [Failed]
*** Failed! (after 7 tests):
Exception:
  toEnum{BlockCode}: tag (326) is outside of enumeration's range (0,320)
  CallStack (from HasCallStack):
    error, called at Data\Text\ICU\Char.hsc:485:17 in text-icu-0.8.0.2-74el0JRRzFBG38VQ4Hqf7Y:Data.Text.ICU.Char
'\73494'
(used seed 2000976820720826537)
```

**Comment by andreasabel** [comment]
Same with '\202654'

**Comment by vshabanov** [comment]
Thank you, just uploaded `text-icu-0.8.0.3` which fixes the issue.

**Comment by vshabanov** [comment]
Some of the tests fail now because they use the pre-72 version of ICU

**Comment by juhp** [comment]
Yes I see for Stackage LTS:

```
             : [Failed]                                                                                                             
           expected: [ChessSymbols,CjkUnifiedIdeographsExtensionH,Kawi]                                                             
            but got: [ChessSymbols,NoBlock,NoBlock]           
```

It would be nice if there was some detection.

**Comment by andreasabel** [comment]
> Some of the tests fail now because they use the pre-72 version of ICU

CI on `ubuntu-22.04` fails now always.  This platform comes with ICU 70.1, see https://github.com/haskell/text-icu/actions/runs/6371163841/job/17292886318#step:8:17.
It would be good if `text-icu` worked smoothly for the latest Ubuntu LTSs (those shipped by github actions) also from the developer perspective.  That means, `cabal test` should run out-of-the-box.

**Comment by juhp** [comment]
We should probably open a new issue or reopen this one?

I need to allow the tests to fail in Nightly too

**Comment by vshabanov** [comment]
Should be fixed in `text-icu-0.8.0.4`

**Comment by andreasabel** [comment]
I deprecated 0.8.0.3 on hackage.

**Comment by juhp** [comment]
If you would like the testsuite re-enabled in Stackage, please open a PR for that, thanks
